### ISSUE TITLE
Additional PersoSim profiles required for special cases

### ISSUE THREAD

**Issue by psytester** [PersoSim/de.persosim.simulator#88]
The predefined PersoSim profiles located in de.persosim.simulator/personalization/profiles needs to be extended with the possible case that an eAT is used for authentication.
At the very beginning of the eAT, he did not have the DG06: Religious/Artistic Name, thus it can return “absent”

Another issue is the “XÖV” character set which contains 9 problematicaly characters.
Those can be displayed faulty in post processing in Webapplication, e.g. in case of wrong CSS definition if the wrong font is used 

```
Codepoint HEX character description
004A+030C = J̌ = J with combining caron
0044+0302 = D̂ = D with combining circumflex accent
004C+0302 = L̂ = L with combining circumflex accent
004D+0302 = M̂ = M with combining circumflex accent
004E+0302 = N̂ = N with combining circumflex accent
0064+0302 = d̂ = d with combining circumflex accent
006C+0302 = l̂ = l with combining circumflex accent
006D+0302 = m̂ = m with combining circumflex accent
006E+0302 = n̂ = n with combining circumflex accent
```

The font „Courier New“ does **NOT** display those 9 character correctly.
The official font ‘UnicodeDoc.ttf’ from BMI supports this, but needs to be installed on client side.
The font „Times New Roman“ or „Arial“ are doing is as well.

**Comment by hfunke** [comment]
Please feel free to create your own profiles with the PersoSim Editor. The editor allows to create citizens with all data groups you need.

**Comment by hfunke** [comment]
Closed.
