### ISSUE TITLE
Startup issues on Big Sur

### ISSUE THREAD

**Issue by marcoliverteschke** [PersoSim/de.persosim.simulator#96]
I'm failing to launch the simulator on macOS Big Sur. I have attached the error log for reference. 

[1634912675871.log](https://github.com/PersoSim/de.persosim.simulator/files/7398477/1634912675871.log)

My Java environment:

```
openjdk 17 2021-09-14
OpenJDK Runtime Environment Temurin-17+35 (build 17+35)
OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)
```

**Comment by hfunke** [comment]
Please use our new version 1.0.1 of PersoSim. This version runs with your Mac.
