### ISSUE TITLE
Problems finding JRE

### ISSUE THREAD

**Issue by siolquadrio** [PersoSim/de.persosim.simulator#98]
I tried to run PersoSim (latest version from website: https://persosim.secunet.com/de/downloads/) on my Mac (MacBook Air, M1 chip, 2020). I followed the instructions given in the manual and installed the Java Runtime Environement beforehand:

<img width="559" alt="image" src="https://github.com/PersoSim/de.persosim.simulator/assets/107039070/1fc6d043-940d-4d17-9b89-831626018600">

However, when I try to launch PersoSim I get following error message:

<img width="567" alt="image" src="https://github.com/PersoSim/de.persosim.simulator/assets/107039070/0f00f627-9070-4626-9cd2-e756061940ef">

Could the M1 chip, which has an arm architecture, also cause problems?
Thank you very much

**Comment by hfunke** [comment]
Currently we work on the macOS version....

**Comment by hfunke** [comment]
We have released version 1.0.1 of PersoSim. This version is also available for macOS and runs on your MBA.
